import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/header"
import Footer from "../components/footer"
import CutoutTextLoader from "../others/loadingscreen"
import React from "react";
import Home from "../WebseiteKomponenten/home";
import Aboutme from "../WebseiteKomponenten/aboutme";
/*import ScrollLinked from "@/others/scroll"; */


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout() {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col min-h-screen">
          <div className="flex-grow">
            <div className='h-screen mb-12 bg-fixed bg-center bg-cover '>
              <Header />
              <main>
                <Home />
                <Aboutme />
              </main>
            </div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}




